FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-stretch-run
WORKDIR /usr/src/app
COPY package.json package-lock.json tsconfig.json ./
COPY ./src ./src
RUN npm install
RUN npm run build
CMD ["npm", "start"]
